language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed chore05/udagram-api-feed:latest
  - docker tag udagram-api-user chore05/udagram-api-user:latest
  - docker tag udagram-reverseproxy chore05/udagram-reverseproxy:latest
  - docker tag udagram-frontend:local chore05/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chore05/udagram-api-feed:latest
  - docker push chore05/udagram-api-user:latest
  - docker push chore05/udagram-reverseproxy:latest
  - docker push chore05/udagram-frontend:latest